### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by viggin** [neofung/xelatex_moderncv#1]
Using TexStudio, get output:

> Process started: xelatex.exe -synctex=1 -interaction=nonstopmode "template_cn_blue".tex
> Qt: Untested Windows version 6.2 detected!
> Error: Command crashed: xelatex.exe -synctex=1 -interaction=nonstopmode "template_cn_blue".tex
> Process exited with error(s)

Can you help me about it?

**Comment by neofung** [comment]
Hi @viggin you can try to compile it with TexLive
